import jsPDF from 'jspdf';
import 'jspdf-autotable';

export const generateReceipt = (transaction) => {
  const doc = new jsPDF();
  
  // Header
  doc.setFontSize(20);
  doc.setTextColor(40, 80, 150);
  doc.text('OFPRS', 105, 20, { align: 'center' });
  
  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  doc.text('Online Fee Payment & Receipt Management System', 105, 28, { align: 'center' });
  
  // Line
  doc.setDrawColor(40, 80, 150);
  doc.setLineWidth(0.5);
  doc.line(20, 32, 190, 32);
  
  // Receipt Title
  doc.setFontSize(16);
  doc.setTextColor(0, 0, 0);
  doc.text('Payment Receipt', 105, 42, { align: 'center' });
  
  // Receipt Details
  doc.setFontSize(10);
  const startY = 55;
  
  doc.text('Receipt Number:', 20, startY);
  doc.text(transaction.receipt_number || 'N/A', 70, startY);
  
  doc.text('Date:', 20, startY + 8);
  doc.text(new Date(transaction.date).toLocaleDateString(), 70, startY + 8);
  
  doc.text('Student Name:', 20, startY + 16);
  doc.text(transaction.student_name || 'N/A', 70, startY + 16);
  
  doc.text('Roll Number:', 20, startY + 24);
  doc.text(transaction.student_rollNo || 'N/A', 70, startY + 24);
  
  doc.text('Department:', 20, startY + 32);
  doc.text(transaction.department || 'N/A', 70, startY + 32);
  
  doc.text('Semester:', 20, startY + 40);
  doc.text(String(transaction.semester) || 'N/A', 70, startY + 40);
  
  // Payment Details Table
  doc.autoTable({
    startY: startY + 50,
    head: [['Fee Type', 'Amount', 'Payment ID', 'Status']],
    body: [[
      transaction.fee_type.toUpperCase(),
      `₹${transaction.amount.toFixed(2)}`,
      transaction.payment_id,
      transaction.status.toUpperCase()
    ]],
    theme: 'grid',
    headStyles: { fillColor: [40, 80, 150] },
    styles: { fontSize: 10 }
  });
  
  // Transaction Details
  const finalY = doc.lastAutoTable.finalY + 10;
  doc.setFontSize(9);
  doc.text('Transaction Details:', 20, finalY);
  doc.text(`Order ID: ${transaction.order_id}`, 20, finalY + 6);
  doc.text(`Academic Year: ${transaction.academic_year || 'N/A'}`, 20, finalY + 12);
  
  // Footer
  doc.setFontSize(8);
  doc.setTextColor(100, 100, 100);
  doc.text('This is a computer-generated receipt. No signature required.', 105, 280, { align: 'center' });
  doc.text('Generated by OFPRS', 105, 285, { align: 'center' });
  
  // Save PDF
  doc.save(`receipt_${transaction.receipt_number}.pdf`);
};

export const formatCurrency = (amount) => {
  return new Intl.NumberFormat('en-IN', {
    style: 'currency',
    currency: 'INR'
  }).format(amount);
};

export const formatDate = (date) => {
  return new Date(date).toLocaleDateString('en-IN', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });
};
